
package org.igv.track;

/**
 * @author jrobinso
 */
public enum DataType {
    OTHER, COPY_NUMBER, GENE_EXPRESSION, CHIP, DNA_METHYLATION, TILING_ARRAY, PHASTCON,
    ALLELE_SPECIFIC_COPY_NUMBER, LOH, MUTATION, RNAI, POOLED_RNAI, CHIP_CHIP, CNV,
    ALLELE_FREQUENCY, COVERAGE, REPMASK, EXPR, GENE, FPKM, PLUGIN, SEQUENCE
}
