#!/bin/sh
prefix=`dirname $(readlink $0 || echo $0)`

# Check whether or not to use the bundled JDK
if [ -d "${prefix}/jdk-11" ]; then
    echo echo "Using bundled JDK."
    JAVA_HOME="${prefix}/jdk-11"
    PATH=$JAVA_HOME/bin:$PATH
else
    echo "Bundled JDK not found.  Using system JDK."
fi

java --module-path="${prefix}/lib" -Xmx1500m \
    @igv.args \
    -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true \
    -Dsun.java2d.uiScale=2 \
    --module=org.igv/org.broad.igv.tools.IgvTools  gui
