/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.views;

/**
 *
 * @author Chantal Roth
 */
public class ChartConfigPanel extends javax.swing.JPanel {

    public static final int TYPE_BAR = 0;
    public static final int TYPE_LINE = 1;
    public static final int TYPE_AREA= 2;
    public static final int TYPE_CANDLE= 3;
    /**
     * Creates new form ChartConfigPanel
     */
    public ChartConfigPanel() {
        initComponents();
    }

    public int getBinSize() {
        Integer bin = (Integer) this.spinbins.getModel().getValue();
        return bin;
    }
    
    public int getChartType() {
        if (this.radioArea.isSelected()) return TYPE_AREA;
        else if (this.radioLine.isSelected()) return TYPE_LINE;
        else return TYPE_BAR;
    }
    public void setChartType(int type) {
        if (type == TYPE_AREA) radioArea.setSelected(true);
        else if (type == TYPE_LINE) radioLine.setSelected(true);
        else radioBar.setSelected(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        spinbins = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        radioLine = new javax.swing.JRadioButton();
        radioBar = new javax.swing.JRadioButton();
        radioArea = new javax.swing.JRadioButton();

        jLabel1.setText("Size of bins:");
        jLabel1.setToolTipText("The granularity of the histogram");

        spinbins.setModel(new javax.swing.SpinnerNumberModel(10, 1, 100, 5));

        jLabel2.setText("Chart type:");

        buttonGroup1.add(radioLine);
        radioLine.setSelected(true);
        radioLine.setText("Line chart");
        radioLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLineActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBar);
        radioBar.setText("Bar chart");

        buttonGroup1.add(radioArea);
        radioArea.setText("Area chart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinbins, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
            .addComponent(radioLine)
            .addComponent(radioBar)
            .addComponent(radioArea)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinbins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioArea))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLineActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radioArea;
    private javax.swing.JRadioButton radioBar;
    private javax.swing.JRadioButton radioLine;
    private javax.swing.JSpinner spinbins;
    // End of variables declaration//GEN-END:variables

    public void setBinSize(int binsize) {
        this.spinbins.setValue(binsize);
    }
}
